// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");

Css.$$global("body", /* :: */[
      Css.backgroundColor(Css.hex("fafafa")),
      /* [] */0
    ]);

var textCenter = Css.style(/* :: */[
      Css.textAlign(Css.center),
      /* [] */0
    ]);

exports.textCenter = textCenter;
/*  Not a pure module */
