// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var MaterialUi_Grid = require("@jsiebern/bs-material-ui/src/MaterialUi_Grid.bs.js");
var MaterialUi_Input = require("@jsiebern/bs-material-ui/src/MaterialUi_Input.bs.js");
var MaterialUi_Paper = require("@jsiebern/bs-material-ui/src/MaterialUi_Paper.bs.js");
var MaterialUi_Button = require("@jsiebern/bs-material-ui/src/MaterialUi_Button.bs.js");
var Footer$ReactTemplate = require("./Footer.bs.js");
var Header$ReactTemplate = require("./Header.bs.js");
var MaterialUi_Color_Red = require("@jsiebern/bs-material-ui/src/MaterialUi_Color_Red.bs.js");
var MaterialUi_TextField = require("@jsiebern/bs-material-ui/src/MaterialUi_TextField.bs.js");
var Styles$ReactTemplate = require("./styles/Styles.bs.js");
var MaterialUi_Color_Blue = require("@jsiebern/bs-material-ui/src/MaterialUi_Color_Blue.bs.js");
var MaterialUi_Typography = require("@jsiebern/bs-material-ui/src/MaterialUi_Typography.bs.js");
var TodoItem$ReactTemplate = require("./TodoItem.bs.js");
var Styles = require("@material-ui/core/styles");
var MaterialUi_MuiThemeProvider = require("@jsiebern/bs-material-ui/src/MaterialUi_MuiThemeProvider.bs.js");

var centered = Css.style(/* :: */[
      Css.alignSelf(Css.center),
      /* :: */[
        Css.margin(Css.auto),
        /* [] */0
      ]
    ]);

var root = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.minHeight(Css.vh(100.0)),
        /* :: */[
          Css.flexDirection(Css.column),
          /* [] */0
        ]
      ]
    ]);

var layoutContainer = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flex(1),
        /* [] */0
      ]
    ]);

var layout = Css.style(/* :: */[
      Css.flex(1),
      /* :: */[
        Css.justifyContent(Css.center),
        /* [] */0
      ]
    ]);

var mainPaper = Css.style(/* :: */[
      Css.minHeight(Css.vh(80.0)),
      /* :: */[
        Css.padding(Css.px(8)),
        /* [] */0
      ]
    ]);

var form = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexDirection(Css.column),
        /* :: */[
          Css.alignItems(Css.center),
          /* [] */0
        ]
      ]
    ]);

var theme = Styles.createMuiTheme({
      palette: {
        primary: {
          main: MaterialUi_Color_Blue.c500
        },
        secondary: {
          main: MaterialUi_Color_Red.c500
        }
      }
    });

var component = ReasonReact.reducerComponent("App");

function handleClick(_, _$1) {
  console.log("clicked!");
  return /* () */0;
}

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = List.length(List.filter((function (t) {
                            return !t[/* complete */2];
                          }))(self[/* state */1][/* todos */0]));
              var match$1 = List.length(List.filter((function (t) {
                            return t[/* complete */2];
                          }))(self[/* state */1][/* todos */0]));
              return ReasonReact.element(undefined, undefined, MaterialUi_MuiThemeProvider.make(undefined, undefined, /* `ObjectGeneric */[
                              -317959944,
                              theme
                            ], /* array */[React.createElement("div", {
                                    className: root
                                  }, ReasonReact.element(undefined, undefined, Header$ReactTemplate.make(/* array */[])), React.createElement("div", {
                                        className: layoutContainer
                                      }, React.createElement("main", {
                                            className: layout
                                          }, ReasonReact.element(undefined, undefined, MaterialUi_Grid.make(undefined, undefined, centered, undefined, undefined, undefined, undefined, undefined, /* V4 */3, /* V6 */5, /* V8 */7, undefined, undefined, undefined, /* V12 */11, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_Paper.make(mainPaper, undefined, undefined, undefined, undefined, undefined, /* array */[
                                                              ReasonReact.element(undefined, undefined, MaterialUi_Typography.make(undefined, Styles$ReactTemplate.textCenter, undefined, undefined, undefined, undefined, undefined, undefined, /* Headline */579538228, undefined, undefined, /* array */["What needs to be done?"])),
                                                              React.createElement("form", {
                                                                    className: form,
                                                                    action: "#",
                                                                    onSubmit: (function () {
                                                                        return Curry._1(self[/* send */3], /* AddTodo */0);
                                                                      })
                                                                  }, ReasonReact.element(undefined, undefined, MaterialUi_Typography.make(undefined, Styles$ReactTemplate.textCenter, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Title:"])), ReasonReact.element(undefined, undefined, MaterialUi_Input.make(undefined, undefined, centered, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function ($$event) {
                                                                              return Curry._1(self[/* send */3], /* ChangeTitle */Block.__(0, [$$event.target.value]));
                                                                            }), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* `String */[
                                                                            -976970511,
                                                                            self[/* state */1][/* newTitle */1]
                                                                          ], undefined, undefined, /* array */[])), ReasonReact.element(undefined, undefined, MaterialUi_Typography.make(undefined, Styles$ReactTemplate.textCenter, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Description (optional):"])), ReasonReact.element(undefined, undefined, MaterialUi_TextField.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function ($$event) {
                                                                              return Curry._1(self[/* send */3], /* ChangeDescription */Block.__(1, [$$event.target.value]));
                                                                            }), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* `String */[
                                                                            -976970511,
                                                                            self[/* state */1][/* newDescription */2]
                                                                          ], undefined, /* array */[])), ReasonReact.element(undefined, undefined, MaterialUi_Button.make(Styles$ReactTemplate.smBtn, /* Primary */-791844958, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "submit", /* Raised */-387916264, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Add to-do"]))),
                                                              match !== 0 ? React.createElement("h2", undefined, "To do") : null,
                                                              ReactDOMRe.createElementVariadic("ul", undefined, $$Array.of_list(List.map((function (t) {
                                                                              return ReasonReact.element(undefined, undefined, TodoItem$ReactTemplate.make(t, (function () {
                                                                                                return Curry._1(self[/* send */3], /* ChangeComplete */Block.__(2, [t]));
                                                                                              }), undefined, /* array */[]));
                                                                            }), List.filter((function (t) {
                                                                                    return !t[/* complete */2];
                                                                                  }))(self[/* state */1][/* todos */0])))),
                                                              match$1 !== 0 ? React.createElement("h2", undefined, "Completed tasks") : null,
                                                              ReactDOMRe.createElementVariadic("ul", undefined, $$Array.of_list(List.map((function (t) {
                                                                              return ReasonReact.element(undefined, undefined, TodoItem$ReactTemplate.make(t, (function () {
                                                                                                return Curry._1(self[/* send */3], /* ChangeComplete */Block.__(2, [t]));
                                                                                              }), (function () {
                                                                                                return Curry._1(self[/* send */3], /* RemoveTodo */Block.__(3, [t]));
                                                                                              }), /* array */[]));
                                                                            }), List.filter((function (t) {
                                                                                    return t[/* complete */2];
                                                                                  }))(self[/* state */1][/* todos */0]))))
                                                            ]))])))), ReasonReact.element(undefined, undefined, Footer$ReactTemplate.make(/* array */[])))]));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* todos : [] */0,
                      /* newTitle */"",
                      /* newDescription */""
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (typeof action === "number") {
                var match = state[/* newTitle */1];
                if (match === "") {
                  return /* NoUpdate */0;
                } else {
                  return /* Update */Block.__(0, [/* record */[
                              /* todos */List.append(state[/* todos */0], /* :: */[
                                    /* record */[
                                      /* title */state[/* newTitle */1],
                                      /* description */state[/* newDescription */2],
                                      /* complete */false
                                    ],
                                    /* [] */0
                                  ]),
                              /* newTitle */"",
                              /* newDescription */""
                            ]]);
                }
              } else {
                switch (action.tag | 0) {
                  case 0 : 
                      return /* Update */Block.__(0, [/* record */[
                                  /* todos */state[/* todos */0],
                                  /* newTitle */action[0],
                                  /* newDescription */state[/* newDescription */2]
                                ]]);
                  case 1 : 
                      return /* Update */Block.__(0, [/* record */[
                                  /* todos */state[/* todos */0],
                                  /* newTitle */state[/* newTitle */1],
                                  /* newDescription */action[0]
                                ]]);
                  case 2 : 
                      var todo = action[0];
                      var updatedTodo_000 = /* title */todo[/* title */0];
                      var updatedTodo_001 = /* description */todo[/* description */1];
                      var updatedTodo_002 = /* complete */!todo[/* complete */2];
                      var updatedTodo = /* record */[
                        updatedTodo_000,
                        updatedTodo_001,
                        updatedTodo_002
                      ];
                      return /* Update */Block.__(0, [/* record */[
                                  /* todos */List.append(List.filter((function (t) {
                                                return Caml_obj.caml_notequal(t, todo);
                                              }))(state[/* todos */0]), /* :: */[
                                        updatedTodo,
                                        /* [] */0
                                      ]),
                                  /* newTitle */state[/* newTitle */1],
                                  /* newDescription */state[/* newDescription */2]
                                ]]);
                  case 3 : 
                      var todo$1 = action[0];
                      return /* Update */Block.__(0, [/* record */[
                                  /* todos */List.filter((function (t) {
                                            return Caml_obj.caml_notequal(t, todo$1);
                                          }))(state[/* todos */0]),
                                  /* newTitle */state[/* newTitle */1],
                                  /* newDescription */state[/* newDescription */2]
                                ]]);
                  
                }
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var $$default = ReasonReact.wrapReasonForJs(component, (function () {
        return make(/* array */[]);
      }));

exports.centered = centered;
exports.root = root;
exports.layoutContainer = layoutContainer;
exports.layout = layout;
exports.mainPaper = mainPaper;
exports.form = form;
exports.theme = theme;
exports.component = component;
exports.handleClick = handleClick;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* centered Not a pure module */
