// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var MaterialUIIcons = require("bs-material-ui-icons/src/MaterialUIIcons.js");
var MaterialUi_Grid = require("@jsiebern/bs-material-ui/src/MaterialUi_Grid.bs.js");
var MaterialUi_Input = require("@jsiebern/bs-material-ui/src/MaterialUi_Input.bs.js");
var MaterialUi_Paper = require("@jsiebern/bs-material-ui/src/MaterialUi_Paper.bs.js");
var MaterialUi_Button = require("@jsiebern/bs-material-ui/src/MaterialUi_Button.bs.js");
var Footer$ReactTemplate = require("./Footer.bs.js");
var Header$ReactTemplate = require("./Header.bs.js");
var MaterialUi_TextField = require("@jsiebern/bs-material-ui/src/MaterialUi_TextField.bs.js");
var Styles$ReactTemplate = require("./styles/Styles.bs.js");
var MaterialUi_Color_Blue = require("@jsiebern/bs-material-ui/src/MaterialUi_Color_Blue.bs.js");
var MaterialUi_Typography = require("@jsiebern/bs-material-ui/src/MaterialUi_Typography.bs.js");
var MaterialUi_Color_Green = require("@jsiebern/bs-material-ui/src/MaterialUi_Color_Green.bs.js");
var TodoItem$ReactTemplate = require("./TodoItem.bs.js");
var Styles = require("@material-ui/core/styles");
var MaterialUi_MuiThemeProvider = require("@jsiebern/bs-material-ui/src/MaterialUi_MuiThemeProvider.bs.js");

var fullWidth = Css.width(Css.pct(100.0));

var flexBox = Css.display(Css.flexBox);

var marginAuto = Css.margin(Css.auto);

var submitBtnContainer = Css.style(/* :: */[
      Css.important(Css.marginTop(Css.em(1.0))),
      /* :: */[
        Css.important(Css.margin(Css.auto)),
        /* [] */0
      ]
    ]);

var centered = Css.style(/* :: */[
      Css.alignSelf(Css.center),
      /* :: */[
        marginAuto,
        /* [] */0
      ]
    ]);

var root = Css.style(/* :: */[
      flexBox,
      /* :: */[
        Css.minHeight(Css.vh(100.0)),
        /* :: */[
          Css.flexDirection(Css.column),
          /* :: */[
            Css.flexGrow(1),
            /* [] */0
          ]
        ]
      ]
    ]);

var layoutContainer = Css.style(/* :: */[
      flexBox,
      /* :: */[
        Css.flex(1),
        /* [] */0
      ]
    ]);

var layout = Css.style(/* :: */[
      Css.flex(1),
      /* :: */[
        Css.justifyContent(Css.center),
        /* :: */[
          Css.maxWidth(Css.pct(100.0)),
          /* [] */0
        ]
      ]
    ]);

var mainPaper = Css.style(/* :: */[
      Css.width(Css.pct(100.0)),
      /* :: */[
        Css.marginTop(Css.em(1.0)),
        /* :: */[
          Css.marginBottom(Css.em(1.0)),
          /* [] */0
        ]
      ]
    ]);

var form = Css.style(/* :: */[
      fullWidth,
      /* :: */[
        Css.alignSelf(Css.center),
        /* :: */[
          Css.alignItems(Css.center),
          /* :: */[
            Css.marginTop(Css.px(10)),
            /* :: */[
              Css.marginBottom(Css.px(10)),
              /* :: */[
                Css.marginLeft(Css.auto),
                /* :: */[
                  Css.marginRight(Css.auto),
                  /* :: */[
                    Css.paddingTop(Css.em(0.5)),
                    /* :: */[
                      Css.paddingBottom(Css.em(0.5)),
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var submitBtn = Css.style(/* :: */[
      Css.alignSelf(Css.center),
      /* :: */[
        Css.important(Css.margin(Css.auto)),
        /* :: */[
          Css.marginTop(Css.em(1.0)),
          /* :: */[
            Css.important(Css.margin(Css.auto)),
            /* :: */[
              Css.important(Css.color(Css.white)),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var textInput = Css.style(/* :: */[
      fullWidth,
      /* [] */0
    ]);

var smallMarginTop = Css.style(/* :: */[
      Css.important(Css.marginTop(Css.em(1.0))),
      /* [] */0
    ]);

var categoryLabel = Css.style(/* :: */[
      Css.paddingBottom(Css.em(0.5)),
      /* :: */[
        Css.paddingTop(Css.em(0.5)),
        /* [] */0
      ]
    ]);

var paperInnerContainer = Css.style(/* :: */[
      Css.padding(Css.em(0.5)),
      /* [] */0
    ]);

var theme = Styles.createMuiTheme({
      palette: {
        primary: {
          main: MaterialUi_Color_Blue.c500
        },
        secondary: {
          main: MaterialUi_Color_Green.c500
        }
      }
    });

var component = ReasonReact.reducerComponent("App");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = List.length(List.filter((function (t) {
                            return !t[/* complete */3];
                          }))(self[/* state */1][/* todos */0]));
              var match$1 = List.length(List.filter((function (t) {
                            return t[/* complete */3];
                          }))(self[/* state */1][/* todos */0]));
              return ReasonReact.element(undefined, undefined, MaterialUi_MuiThemeProvider.make(undefined, undefined, /* `ObjectGeneric */[
                              -317959944,
                              theme
                            ], /* array */[React.createElement("div", {
                                    className: root
                                  }, ReasonReact.element(undefined, undefined, Header$ReactTemplate.make(/* array */[])), React.createElement("div", {
                                        className: layoutContainer
                                      }, React.createElement("main", {
                                            className: layout
                                          }, ReasonReact.element(undefined, undefined, MaterialUi_Grid.make(undefined, undefined, centered, undefined, undefined, /* Column */-81804554, undefined, undefined, /* V4 */3, /* V6 */5, /* V8 */7, /* V24 */3, undefined, undefined, /* V12 */11, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_Paper.make(mainPaper, undefined, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_Grid.make(undefined, undefined, paperInnerContainer, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* V12 */11, undefined, undefined, undefined, /* array */[
                                                                        ReasonReact.element(undefined, undefined, MaterialUi_Grid.make(undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* V12 */11, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_Typography.make(undefined, Styles$ReactTemplate.textCenter, undefined, undefined, undefined, undefined, undefined, undefined, /* Headline */579538228, undefined, undefined, /* array */["What would you like to do?"]))])),
                                                                        ReasonReact.element(undefined, undefined, MaterialUi_Grid.make(undefined, undefined, centered, undefined, undefined, /* Column */-81804554, true, /* Center */980392437, undefined, undefined, undefined, undefined, undefined, undefined, /* V12 */11, undefined, undefined, undefined, /* array */[React.createElement("form", {
                                                                                        className: form,
                                                                                        action: "#",
                                                                                        onSubmit: (function () {
                                                                                            return Curry._1(self[/* send */3], /* AddTodo */0);
                                                                                          })
                                                                                      }, ReasonReact.element(undefined, undefined, MaterialUi_Grid.make(undefined, undefined, centered, undefined, true, /* Column */-81804554, undefined, /* Center */980392437, /* V5 */4, /* V7 */6, /* V9 */8, undefined, undefined, undefined, /* V11 */10, undefined, undefined, undefined, /* array */[
                                                                                                ReasonReact.element(undefined, undefined, MaterialUi_Grid.make(undefined, undefined, undefined, undefined, undefined, undefined, true, /* Center */980392437, undefined, undefined, undefined, undefined, undefined, undefined, /* V12 */11, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_Input.make(undefined, undefined, textInput, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function ($$event) {
                                                                                                                      return Curry._1(self[/* send */3], /* ChangeTitle */Block.__(0, [$$event.target.value]));
                                                                                                                    }), undefined, undefined, undefined, undefined, undefined, "Title", undefined, undefined, undefined, undefined, undefined, /* `String */[
                                                                                                                    -976970511,
                                                                                                                    self[/* state */1][/* newTitle */1]
                                                                                                                  ], undefined, undefined, /* array */[]))])),
                                                                                                ReasonReact.element(undefined, undefined, MaterialUi_Grid.make(undefined, undefined, undefined, undefined, undefined, undefined, true, /* Center */980392437, undefined, undefined, undefined, undefined, undefined, undefined, /* V12 */11, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_TextField.make(undefined, undefined, textInput, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, (function ($$event) {
                                                                                                                      return Curry._1(self[/* send */3], /* ChangeDescription */Block.__(1, [$$event.target.value]));
                                                                                                                    }), undefined, "Description (optional)", undefined, /* `Int */[
                                                                                                                    3654863,
                                                                                                                    4
                                                                                                                  ], undefined, undefined, undefined, undefined, /* `String */[
                                                                                                                    -976970511,
                                                                                                                    self[/* state */1][/* newDescription */2]
                                                                                                                  ], undefined, /* array */[]))])),
                                                                                                ReasonReact.element(undefined, undefined, MaterialUi_Grid.make(undefined, undefined, submitBtnContainer, undefined, undefined, undefined, true, /* Center */980392437, undefined, undefined, undefined, undefined, undefined, undefined, /* V12 */11, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_Button.make(submitBtn, /* Secondary */67972948, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "submit", /* Fab */3502759, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUIIcons.Add[/* make */0](/* array */[]))]))]))
                                                                                              ])))])),
                                                                        ReasonReact.element(undefined, undefined, MaterialUi_Grid.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* V24 */3, undefined, undefined, /* V12 */11, undefined, undefined, undefined, /* array */[match !== 0 ? ReasonReact.element(undefined, undefined, MaterialUi_Typography.make(undefined, categoryLabel, undefined, undefined, undefined, undefined, undefined, undefined, /* Title */594052472, undefined, undefined, /* array */["To do"])) : null])),
                                                                        ReasonReact.element(undefined, undefined, MaterialUi_Grid.make(undefined, undefined, undefined, undefined, undefined, undefined, true, /* Center */980392437, undefined, undefined, undefined, undefined, undefined, undefined, /* V12 */11, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_Grid.make(undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, /* V8 */1, undefined, undefined, undefined, undefined, undefined, undefined, $$Array.of_list(List.map((function (t) {
                                                                                                      return ReasonReact.element(undefined, undefined, TodoItem$ReactTemplate.make(t, (function () {
                                                                                                                        return Curry._1(self[/* send */3], /* ChangeComplete */Block.__(2, [t]));
                                                                                                                      }), undefined, /* array */[]));
                                                                                                    }), List.filter((function (t) {
                                                                                                            return !t[/* complete */3];
                                                                                                          }))(self[/* state */1][/* todos */0])))))])),
                                                                        ReasonReact.element(undefined, undefined, MaterialUi_Grid.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* V24 */3, undefined, undefined, /* V12 */11, undefined, undefined, undefined, /* array */[match$1 !== 0 ? ReasonReact.element(undefined, undefined, MaterialUi_Typography.make(undefined, categoryLabel, undefined, undefined, undefined, undefined, undefined, undefined, /* Title */594052472, undefined, undefined, /* array */["Completed tasks"])) : null])),
                                                                        ReasonReact.element(undefined, undefined, MaterialUi_Grid.make(undefined, undefined, undefined, undefined, undefined, undefined, true, /* Center */980392437, undefined, undefined, undefined, undefined, undefined, undefined, /* V12 */11, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_Grid.make(undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, /* V8 */1, undefined, undefined, undefined, undefined, undefined, undefined, $$Array.of_list(List.map((function (t) {
                                                                                                      return ReasonReact.element(undefined, undefined, TodoItem$ReactTemplate.make(t, (function () {
                                                                                                                        return Curry._1(self[/* send */3], /* ChangeComplete */Block.__(2, [t]));
                                                                                                                      }), (function () {
                                                                                                                        return Curry._1(self[/* send */3], /* RemoveTodo */Block.__(3, [t]));
                                                                                                                      }), /* array */[]));
                                                                                                    }), List.filter((function (t) {
                                                                                                            return t[/* complete */3];
                                                                                                          }))(self[/* state */1][/* todos */0])))))]))
                                                                      ]))]))])))), ReasonReact.element(undefined, undefined, Footer$ReactTemplate.make(/* array */[])))]));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* todos : [] */0,
                      /* newTitle */"",
                      /* newDescription */"",
                      /* lastId */0
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (typeof action === "number") {
                var match = state[/* newTitle */1];
                if (match === "") {
                  return /* NoUpdate */0;
                } else {
                  return /* Update */Block.__(0, [/* record */[
                              /* todos */List.append(state[/* todos */0], /* :: */[
                                    /* record */[
                                      /* id */state[/* lastId */3] + 1 | 0,
                                      /* title */state[/* newTitle */1],
                                      /* description */state[/* newDescription */2],
                                      /* complete */false
                                    ],
                                    /* [] */0
                                  ]),
                              /* newTitle */"",
                              /* newDescription */"",
                              /* lastId */state[/* lastId */3] + 1 | 0
                            ]]);
                }
              } else {
                switch (action.tag | 0) {
                  case 0 : 
                      return /* Update */Block.__(0, [/* record */[
                                  /* todos */state[/* todos */0],
                                  /* newTitle */action[0],
                                  /* newDescription */state[/* newDescription */2],
                                  /* lastId */state[/* lastId */3]
                                ]]);
                  case 1 : 
                      return /* Update */Block.__(0, [/* record */[
                                  /* todos */state[/* todos */0],
                                  /* newTitle */state[/* newTitle */1],
                                  /* newDescription */action[0],
                                  /* lastId */state[/* lastId */3]
                                ]]);
                  case 2 : 
                      var todo = action[0];
                      var updatedTodo_000 = /* id */todo[/* id */0];
                      var updatedTodo_001 = /* title */todo[/* title */1];
                      var updatedTodo_002 = /* description */todo[/* description */2];
                      var updatedTodo_003 = /* complete */!todo[/* complete */3];
                      var updatedTodo = /* record */[
                        updatedTodo_000,
                        updatedTodo_001,
                        updatedTodo_002,
                        updatedTodo_003
                      ];
                      return /* Update */Block.__(0, [/* record */[
                                  /* todos */List.append(List.filter((function (t) {
                                                return t[/* id */0] !== todo[/* id */0];
                                              }))(state[/* todos */0]), /* :: */[
                                        updatedTodo,
                                        /* [] */0
                                      ]),
                                  /* newTitle */state[/* newTitle */1],
                                  /* newDescription */state[/* newDescription */2],
                                  /* lastId */state[/* lastId */3]
                                ]]);
                  case 3 : 
                      var todo$1 = action[0];
                      return /* Update */Block.__(0, [/* record */[
                                  /* todos */List.filter((function (t) {
                                            return t[/* id */0] !== todo$1[/* id */0];
                                          }))(state[/* todos */0]),
                                  /* newTitle */state[/* newTitle */1],
                                  /* newDescription */state[/* newDescription */2],
                                  /* lastId */state[/* lastId */3]
                                ]]);
                  
                }
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var $$default = ReasonReact.wrapReasonForJs(component, (function () {
        return make(/* array */[]);
      }));

exports.fullWidth = fullWidth;
exports.flexBox = flexBox;
exports.marginAuto = marginAuto;
exports.submitBtnContainer = submitBtnContainer;
exports.centered = centered;
exports.root = root;
exports.layoutContainer = layoutContainer;
exports.layout = layout;
exports.mainPaper = mainPaper;
exports.form = form;
exports.submitBtn = submitBtn;
exports.textInput = textInput;
exports.smallMarginTop = smallMarginTop;
exports.categoryLabel = categoryLabel;
exports.paperInnerContainer = paperInnerContainer;
exports.theme = theme;
exports.component = component;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* fullWidth Not a pure module */
