// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var MaterialUi_Typography = require("@jsiebern/bs-material-ui/src/MaterialUi_Typography.bs.js");

var component = ReasonReact.statelessComponent("Footer");

var footerClass = Css.style(/* :: */[
      Css.backgroundColor(Css.aliceblue),
      /* :: */[
        Css.color(Css.white),
        /* [] */0
      ]
    ]);

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("footer", {
                          className: footerClass
                        }, ReasonReact.element(undefined, undefined, MaterialUi_Typography.make(/* Center */980392437, undefined, /* TextSecondary */-507693849, undefined, true, undefined, undefined, undefined, /* Body1 */-904051921, undefined, undefined, /* array */["Copyright (c) 2018 Tanner Goins"])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.footerClass = footerClass;
exports.make = make;
/* component Not a pure module */
