// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("TodoItem");

function make(todo, onChangeState, onDelete, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              var match = todo[/* complete */2];
              return React.createElement("li", undefined, match ? React.createElement("div", undefined, React.createElement("button", {
                                    type: "button",
                                    onClick: onDelete !== undefined ? onDelete : (function () {
                                          return /* () */0;
                                        })
                                  }, "Delete"), React.createElement("button", {
                                    type: "button",
                                    onClick: onChangeState !== undefined ? onChangeState : (function () {
                                          return /* () */0;
                                        })
                                  }, "Set to-do")) : React.createElement("button", {
                                type: "button",
                                onClick: onChangeState !== undefined ? onChangeState : (function () {
                                      return /* () */0;
                                    })
                              }, "Mark as done"), React.createElement("h3", undefined, todo[/* title */0]), React.createElement("p", undefined, todo[/* description */1]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
