// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");

function muiToCss(muiString) {
  return $$String.sub(muiString, 1, muiString.length - 1 | 0);
}

exports.muiToCss = muiToCss;
/* No side effect */
